dataset:
  feature_kwargs:
    feature_type: hog3x3

model:
  name: moe
  kwargs:
    num_experts: 128
    expert_kwargs:
      activation: softmax
      use_bias: true
    mixture_kwargs:
      gate_use_bias: true
