dataset:
  feature_kwargs:
    feature_type: BoW
    bow_vocab_size: 1000

model:
  name: cen
  kwargs:
    explainer_name: affine
    explainer_kwargs:
      gen_use_bias: true
      use_bias: true
      entropy_regularizer:
        class_name: ctx_cond_neg_ent
        config:
          coeff: 1e-1
          num_samples: 256
          stddev: 0.2
      kernel_regularizer:
        class_name: l1_l2
        config:
          l1: 1e-5
          l2: 0.
      gen_kernel_regularizer:
        class_name: l1_l2
        config:
          l1: 1e-5
          l2: 1e-6
    top_dense_layers: 1
    top_dense_units: 256
    top_dense_activation: relu
    top_dense_dropout: 0.5
